platform :ios, '6.0'

pod 'GDataXML-HTML',       '~> 1.1.0'
pod 'DTFoundation/DTHTMLParser', '~> 1.5.0'
pod 'AFNetworking', '~> 1.3.1'
pod 'ErrorKit/Core', '~> 0.0.5'

pod 'HCDownload', :podspec => './HCDownload.podspec'